imports:
    - php

filter:
    paths: ["app/Models/*", "routes/web.php"]
    excluded_paths: [vendor/*, app/Models/User.php]

tools:
    php_analyzer: true

build:
    project_setup:
        override:
            - true
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
        analysis:
              tests:
                override:
                  - php-scrutinizer-run

    tests:
        before:
            - cp .env.scrutinizer .env
            - php artisan key:generate
        override:
            -
                command: make phpunit
                coverage:
                    file: build/coverage.clover
                    format: php-clover
